version: '3'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        volumes:
            - ./app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"

    php:    
        container_name: php
        build:
            context: .
            dockerfile: ./php/Dockerfile
        
        volumes:
            - ./app/:/var/www/html/
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"


        